<a href="https://colab.research.google.com/github/WonJunPark/pytorch_tutorials/blob/master/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
a = torch.empty(5, 7, dtype=torch.float)

In [2]:
a = torch.randn(5, 7, dtype=torch.double)
print(a)
print(a.size())

tensor([[-0.7638,  1.5508,  0.8655, -1.2219,  0.3260,  0.3114, -1.2575],
        [-0.8164,  0.9532,  0.6754,  0.3693,  2.3825, -0.4921,  0.8485],
        [ 1.7835,  1.5344,  0.3317,  1.0133, -0.3981,  1.0270, -0.9160],
        [ 0.3088,  1.1505, -0.4357, -0.1609,  0.2623,  1.6203,  0.6514],
        [-0.0187,  0.2434, -1.7305,  1.5200,  0.9916,  1.1819,  0.8972]],
       dtype=torch.float64)
torch.Size([5, 7])


In [12]:
a.fill_(3.5)
b = a.add(4.0)
print(a,b)

tensor([[3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000]],
       dtype=torch.float64) tensor([[7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000]],
       dtype=torch.float64)


In [16]:
c = a.add_(4.0)
print(a,c)

tensor([[19.5000, 19.5000, 19.5000, 19.5000, 19.5000, 19.5000, 19.5000],
        [19.5000, 19.5000, 19.5000, 19.5000, 19.5000, 19.5000, 19.5000],
        [19.5000, 19.5000, 19.5000, 19.5000, 19.5000, 19.5000, 19.5000],
        [19.5000, 19.5000, 19.5000, 19.5000, 19.5000, 19.5000, 19.5000],
        [19.5000, 19.5000, 19.5000, 19.5000, 19.5000, 19.5000, 19.5000]],
       dtype=torch.float64) tensor([[19.5000, 19.5000, 19.5000, 19.5000, 19.5000, 19.5000, 19.5000],
        [19.5000, 19.5000, 19.5000, 19.5000, 19.5000, 19.5000, 19.5000],
        [19.5000, 19.5000, 19.5000, 19.5000, 19.5000, 19.5000, 19.5000],
        [19.5000, 19.5000, 19.5000, 19.5000, 19.5000, 19.5000, 19.5000],
        [19.5000, 19.5000, 19.5000, 19.5000, 19.5000, 19.5000, 19.5000]],
       dtype=torch.float64)


In [17]:
print(b)

tensor([[7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000]],
       dtype=torch.float64)


In [19]:
a.fill_(3.5)
b = a.add(4.0)
print(a,b)
b = a.add(4.0)
print(a,b)

tensor([[3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000]],
       dtype=torch.float64) tensor([[7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000]],
       dtype=torch.float64)
tensor([[3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3

In [21]:
a.fill_(3.5)
c = a.add_(4.0)
print(a,c)
c = a.add_(4.0)
print(a,c)

tensor([[7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000]],
       dtype=torch.float64) tensor([[7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000]],
       dtype=torch.float64)
tensor([[11.5000, 11.5000, 11.5000, 11.5000, 11.5000, 11.5000, 11.5000],
        [11.5000, 11.5000, 11.5000, 11.5000, 11.5000, 11.5000, 11.5000],
        [11.5000, 11.5000, 11.5000, 11.5000, 11.5000, 11.5000, 11.5000],
        [11.5000, 11.5000, 11.5000, 11.5000, 11.5000, 11.5000, 

In [25]:
b = a[0, 3]  # select 1st row, 4th column from a
print(b)
b = a[:, 3:5]  # selects all rows, 4th column and  5th column from a
print(b)

tensor(11.5000, dtype=torch.float64)
tensor([[11.5000, 11.5000],
        [11.5000, 11.5000],
        [11.5000, 11.5000],
        [11.5000, 11.5000],
        [11.5000, 11.5000]], dtype=torch.float64)


In [36]:
x = torch.ones(5, 5)
print(x)

z = torch.empty(5, 2)
z[:, 0] = 10
z[:, 1] = 100
print(z)

x.index_add_(1, torch.tensor([4, 0], dtype=torch.long), z)
print(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[ 10., 100.],
        [ 10., 100.],
        [ 10., 100.],
        [ 10., 100.],
        [ 10., 100.]])
tensor([[101.,   1.,   1.,   1.,  11.],
        [101.,   1.,   1.,   1.,  11.],
        [101.,   1.,   1.,   1.,  11.],
        [101.,   1.,   1.,   1.,  11.],
        [101.,   1.,   1.,   1.,  11.]])


In [37]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [39]:
b = a.numpy()
print(b)

[2. 2. 2. 2. 2.]


In [40]:
a.add_(1)
print(a)
print(b)    # see how the numpy array changed in value

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [41]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)  # see how changing the np array changed the torch Tensor automatically

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [0]:
# 이 코드는 CUDA가 사용 가능한 환경에서만 실행됩니다.
if torch.cuda.is_available():

    # LongTensor를 생성하고 이를 torch.cuda.LongTensor로 GPU로 옮깁니다.
    a = torch.full((10,), 3, device=torch.device("cuda"))
    print(type(a))
    b = a.to(torch.device("cpu"))
    # CPU로 다시 전송을 하면, torch.LongTensor로 되돌아옵니다.

In [43]:
import torch

x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [49]:
print(x.data)
print(x.grad)
print(x.grad_fn)  # we've created x ourselves

tensor([[1., 1.],
        [1., 1.]])
None
None


In [51]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [53]:
z = y * y * 3
out = z.mean()

print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [54]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [56]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [63]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
y.backward(torch.ones(2, 2), retain_graph=True)
# retain_variables flag는 내부 버퍼가 사라지는 것을 막아줍니다.
print(x.grad)
print(x)
print(y.grad)
print(y)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [58]:
z = y * y
print(z)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<MulBackward0>)


In [62]:
gradient = torch.randn(2, 2)

# retain_variable 을 지정하지 않았다면 오류가 발생할 것입니다.
y.backward(gradient)

print(x.grad)

tensor([[2.9061, 0.6146],
        [1.9736, 0.1688]])


In [64]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
