<a href="https://colab.research.google.com/github/WonJunPark/pytorch_tutorials/blob/master/what_is_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import print_function
import torch

In [13]:
x = torch.empty(5, 3)
print(x)

tensor([[5.1509e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [5.3691e-05, 3.2770e-09, 4.2932e-08],
        [6.7083e-10, 3.2690e+21, 1.7000e+22],
        [1.0664e-08, 1.0432e+21, 8.0312e-01]])


In [8]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5480, 0.8406, 0.9236],
        [0.0744, 0.4183, 0.1195],
        [0.6648, 0.3693, 0.3106],
        [0.1209, 0.6160, 0.4374],
        [0.6046, 0.7374, 0.8031]])


In [14]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [15]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [16]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.0672,  1.1607, -0.4109],
        [ 1.9600,  1.1639,  0.4592],
        [ 1.3633,  0.1376, -0.5118],
        [ 0.5754, -0.6360, -0.2977],
        [-1.8101,  0.0310,  0.0082]])


In [17]:
print(x.size())

torch.Size([5, 3])


In [18]:
type(x)

torch.Tensor

In [20]:
x

tensor([[-1.0672,  1.1607, -0.4109],
        [ 1.9600,  1.1639,  0.4592],
        [ 1.3633,  0.1376, -0.5118],
        [ 0.5754, -0.6360, -0.2977],
        [-1.8101,  0.0310,  0.0082]])

In [21]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.1623,  1.6949,  0.3680],
        [ 2.6892,  1.2128,  1.4480],
        [ 2.1487,  1.0511, -0.0955],
        [ 0.9672,  0.3054,  0.1547],
        [-0.9435,  0.8258,  0.8526]])


In [22]:
print(torch.add(x, y))

tensor([[-0.1623,  1.6949,  0.3680],
        [ 2.6892,  1.2128,  1.4480],
        [ 2.1487,  1.0511, -0.0955],
        [ 0.9672,  0.3054,  0.1547],
        [-0.9435,  0.8258,  0.8526]])


In [23]:
print(torch.add(x, y))

tensor([[-0.1623,  1.6949,  0.3680],
        [ 2.6892,  1.2128,  1.4480],
        [ 2.1487,  1.0511, -0.0955],
        [ 0.9672,  0.3054,  0.1547],
        [-0.9435,  0.8258,  0.8526]])


In [24]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.1623,  1.6949,  0.3680],
        [ 2.6892,  1.2128,  1.4480],
        [ 2.1487,  1.0511, -0.0955],
        [ 0.9672,  0.3054,  0.1547],
        [-0.9435,  0.8258,  0.8526]])


In [25]:
result = x+y
print(result)

tensor([[-0.1623,  1.6949,  0.3680],
        [ 2.6892,  1.2128,  1.4480],
        [ 2.1487,  1.0511, -0.0955],
        [ 0.9672,  0.3054,  0.1547],
        [-0.9435,  0.8258,  0.8526]])


In [26]:
# y에 x 더하기
y.add_(x)
print(y)

tensor([[-0.1623,  1.6949,  0.3680],
        [ 2.6892,  1.2128,  1.4480],
        [ 2.1487,  1.0511, -0.0955],
        [ 0.9672,  0.3054,  0.1547],
        [-0.9435,  0.8258,  0.8526]])


In [27]:
print(x[:, 1])

tensor([ 1.1607,  1.1639,  0.1376, -0.6360,  0.0310])


In [28]:
print(x[:, 1])

tensor([ 1.1607,  1.1639,  0.1376, -0.6360,  0.0310])


In [39]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # 사이즈가 -1인 경우 다른 차원들을 사용하여 유추합니다.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [34]:
x

tensor([[-0.0472, -0.4719, -0.3174,  0.8370],
        [ 0.3975, -0.5542,  0.1529, -0.4367],
        [ 0.2017, -1.4688,  1.1818, -0.6947],
        [-0.0694, -0.1161,  0.9646, -0.7163]])

In [35]:
y

tensor([-0.0472, -0.4719, -0.3174,  0.8370,  0.3975, -0.5542,  0.1529, -0.4367,
         0.2017, -1.4688,  1.1818, -0.6947, -0.0694, -0.1161,  0.9646, -0.7163])

In [36]:
z

tensor([[-0.0472, -0.4719, -0.3174,  0.8370,  0.3975, -0.5542,  0.1529, -0.4367],
        [ 0.2017, -1.4688,  1.1818, -0.6947, -0.0694, -0.1161,  0.9646, -0.7163]])

In [37]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.1099])
-1.1099469661712646


In [40]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [41]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [42]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [43]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [0]:
# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# ``torch.device`` 를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.
if torch.cuda.is_available():
    device = torch.device("cuda")          # CUDA 장치 객체(Device Object)로
    y = torch.ones_like(x, device=device)  # GPU 상에 바로(directly) tensor를 생성하거나
    x = x.to(device)                       # 단지 ``.to("cuda")`` 라고만 작성하면 됩니다.
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 는 dtype도 함께 변경합니다!